"""add voiceModel to config

Revision ID: 3903394e1e7d
Revises: d7b383a16611
Create Date: 2023-08-20 18:54:10.740806

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3903394e1e7d'
down_revision: Union[str, None] = 'd7b383a16611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userconfigs', sa.Column('voiceModel', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userconfigs', 'voiceModel')
    # ### end Alembic commands ###
