"""add timezones to userConfig

Revision ID: 41872c2a47bc
Revises: 1429287bcfdd
Create Date: 2024-07-12 10:58:53.021071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41872c2a47bc'
down_revision: Union[str, None] = '1429287bcfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userconfigs', sa.Column('timeZone', sa.String(), server_default='UTC', nullable=False))
    op.add_column('userconfigs', sa.Column('use24HourTime', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userconfigs', 'timeZone')
    op.drop_column('userconfigs', 'use24HourTime')
    # ### end Alembic commands ###
