"""init database

Revision ID: 645bdeee0ac6
Revises: 
Create Date: 2023-08-12 21:22:50.332557

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '645bdeee0ac6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'guildconfigs',
        sa.Column('guildId', sa.BIGINT(), nullable=False),
        sa.Column('ayy', sa.Boolean(), nullable=False),
        sa.Column('tikTok', sa.Boolean(), nullable=False),
        sa.Column('veryCool', sa.Boolean(), nullable=False),
        sa.Column('collectVoiceData', sa.Boolean(), nullable=False),
        sa.Column('firstAmendment', sa.Boolean(), nullable=False),
        sa.Column('privateOnePersonVCs', sa.Boolean(), nullable=False),
        sa.Column('transcribeVoiceMessages', sa.Boolean(), nullable=False),
        sa.Column('minecraft', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('guildId'),
    )
    op.create_table(
        'reminders',
        sa.Column('target', sa.BIGINT(), nullable=False),
        sa.Column('owner', sa.BIGINT(), nullable=False),
        sa.Column('guildId', sa.BIGINT(), nullable=True),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('next_remind', sa.DateTime(), nullable=False),
        sa.Column('frequency', sa.Interval(), nullable=True),
        sa.Column('require_clearing', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sugeryzonenames',
        sa.Column('VERYLOW', sa.String(), nullable=False),
        sa.Column('LOW', sa.String(), nullable=False),
        sa.Column('NORMAL', sa.String(), nullable=False),
        sa.Column('HIGH', sa.String(), nullable=False),
        sa.Column('VERYHIGH', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'userconfigs',
        sa.Column('userId', sa.BIGINT(), nullable=False),
        sa.Column('ringable', sa.Boolean(), nullable=False),
        sa.Column('collectVoiceData', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('userId'),
    )
    op.create_table(
        'voiceStats',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('longest_session', sa.Interval(), nullable=False),
        sa.Column('currently_running', sa.Boolean(), nullable=False),
        sa.Column('average_duration', sa.Interval(), nullable=False),
        sa.Column('total_sessions', sa.Integer(), nullable=False),
        sa.Column('recently_ended', sa.Boolean(), nullable=False),
        sa.Column('last_started', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'voicenames',
        sa.Column('userId', sa.BIGINT(), nullable=False),
        sa.Column('channelId', sa.BIGINT(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('userId', 'channelId'),
    )
    op.create_table(
        'sugeryusers',
        sa.Column('guildId', sa.BIGINT(), nullable=False),
        sa.Column('userId', sa.BIGINT(), nullable=False),
        sa.Column('baseURL', sa.String(), nullable=False),
        sa.Column('namesId', sa.UUID(), nullable=False),
        sa.Column('constantAlerts', sa.BIGINT(), nullable=True),
        sa.Column('alertsTranslationsId', sa.UUID(), nullable=True),
        sa.Column('lastGroup', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['alertsTranslationsId'],
            ['sugeryzonenames.id'],
        ),
        sa.ForeignKeyConstraint(
            ['namesId'],
            ['sugeryzonenames.id'],
        ),
        sa.PrimaryKeyConstraint('guildId', 'userId'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sugeryusers')
    op.drop_table('voicenames')
    op.drop_table('voiceStats')
    op.drop_table('userconfigs')
    op.drop_table('sugeryzonenames')
    op.drop_table('reminders')
    op.drop_table('guildconfigs')
    # ### end Alembic commands ###
