"""add marker for 'has been run and knows how to disable that feature'

Revision ID: ca032db10a65
Revises: e2d7febddf07
Create Date: 2024-04-22 19:32:00.000875

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ca032db10a65'
down_revision: Union[str, None] = 'e2d7febddf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'userconfigs', sa.Column('hasBeenRung', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userconfigs', 'hasBeenRung')
    # ### end Alembic commands ###
