"""store thresholds in db

Revision ID: d7b383a16611
Revises: 645bdeee0ac6
Create Date: 2023-08-17 09:07:45.079255

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7b383a16611'
down_revision: Union[str, None] = '645bdeee0ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'suthresholds',
        sa.Column('veryHigh', sa.Integer(), nullable=False),
        sa.Column('high', sa.Integer(), nullable=False),
        sa.Column('low', sa.Integer(), nullable=False),
        sa.Column('veryLow', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('sugeryusers', sa.Column('thresholdsId', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sugeryusers', 'suthresholds', ['thresholdsId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sugeryusers', type_='foreignkey')
    op.drop_column('sugeryusers', 'thresholdsId')
    op.drop_table('suthresholds')
    # ### end Alembic commands ###
