"""use enum for sugery feature

Revision ID: e2d7febddf07
Revises: 1b5c4ba46fbe
Create Date: 2024-04-20 13:17:57.224441

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2d7febddf07'
down_revision: Union[str, None] = '1b5c4ba46fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE sugeryzone AS ENUM ('VERYLOW', 'LOW', 'NORMAL', 'HIGH', 'VERYHIGH')")
    op.drop_column('sugeryusers', 'lastGroup')
    op.add_column(
        'sugeryusers',
        sa.Column(
            'lastGroup', sa.Enum('VERYLOW', 'LOW', 'NORMAL', 'HIGH', 'VERYHIGH', name='sugeryzone'), nullable=False
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sugeryusers', 'lastGroup')
    op.add_column('sugeryusers', sa.Column('lastGroup', sa.VARCHAR(), nullable=True))
    op.execute("DROP TYPE sugeryzone")

    # ### end Alembic commands ###
